### PR TITLE
Only attempt withdrawal if all previous successful

### PR DESCRIPTION
**Pull request by dapplion**
- Comparing with gas data from https://github.com/gnosischain/deposit-contract/pull/27 saves 25% on the failed case at no extra cost for the happy case

### CODE REVIEW

**Review by Barichek — COMMENTED** [review]
I think this logic is not correct. In case some old withdrawal cannot be made using the queue (for example, because it is a withdrawal for too large amount, or we did not take into account (or was changed) some token invariant) all new withdrawals will fail by default.

**Comment by dapplion** [comment]
In the counter-example you provide, this single "corrupt" withdrawal would block all pending withdrawals right? Why is it okay to break early on retries but not break early on all?

**Comment by Barichek** [comment]
> In the counter-example you provide, this single "corrupt" withdrawal would block all pending withdrawals right? Why is it okay to break early on retries but not break early on all?

As far as I understand, the use of the queue of failed withdrawals should only be "a convenient automatic way to process them", and not affect the logic of execution of new withdrawals. So processing of new withdrawals should not rely on the success of the process of failed withdrawals. That is why I think we should try to process new withdrawals even if some corrupted one is in the queue.

**Comment by dapplion** [comment]
> > In the counter-example you provide, this single "corrupt" withdrawal would block all pending withdrawals right? Why is it okay to break early on retries but not break early on all?
> 
> As far as I understand, the use of the queue of failed withdrawals should only be "a convenient automatic way to process them", and not affect the logic of execution of new withdrawals. So processing of new withdrawals should not rely on the success of the process of failed withdrawals. That is why I think we should try to process new withdrawals even if some corrupted one is in the queue.

Agree with above

**Pull request closed without merging**
