### PR TITLE
Test SBCTesnetDeployer

### PR DESCRIPTION
**Pull request by dapplion**
- Test SBCTesnetDeployer to ease devnet setup for https://github.com/gnosischain/deposit-contract/pull/25

### CODE REVIEW

**Review by Barichek — COMMENTED** [review]
Seems to be correct testnet deployer contract!

**Comment by dapplion** [comment]
> Seems to be correct testnet deployer contract!

Issue is that transaction reverts, is it possible to get more information about why? 
```
  1) Contract: SBCTesnetDeployer
       "before each" hook for "Should deploy and collect addresses":
     Error: Returned error: VM Exception while processing transaction: revert
      at Context.<anonymous> (test/testnetDeployer.js:11:50)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by Barichek** [comment]
> > Seems to be correct testnet deployer contract!
> 
> Issue is that transaction reverts, is it possible to get more information about why?
> 
> ```
>   1) Contract: SBCTesnetDeployer
>        "before each" hook for "Should deploy and collect addresses":
>      Error: Returned error: VM Exception while processing transaction: revert
>       at Context.<anonymous> (test/testnetDeployer.js:11:50)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```

Ah, I see. You are creating `depositContractProxy` contract with `_admin` as an owner. This deployment method uses `upgradeTo` function (that is because of cyclic dependencies), but deployer contract is not an owner. I will fix it and push to this branch.

**Comment by Barichek** [comment]
> You are creating depositContractProxy contract with _admin as an owner.

Ok, that was not the only problem. I think the main problem is that the bytecode of the `SBCTesnetDeployer` [is greater than `2^14+2^13`](https://eips.ethereum.org/EIPS/eip-170). You should divide logic of it. Anyway I will push the fix of the previous problem.

**Pull request closed without merging**
